### ISSUE TITLE
itchat停掉了

### ISSUE THREAD

**Issue by EillotY** [CharlesPikachu/pikachuwechat#2]
使用了本项目，但是启动之后，少了扫描登陆的操作，直接显示登陆成功了（其实就是没有登陆）.....是不是itchat停掉了缘故才会这样？

**Comment by CharlesPikachu** [comment]
...我没咋用itchat，随手搜了一下，好像腾讯把API给封了了吧，所以登陆不了了。。。我有空再看看吧。

**Comment by CharlesPikachu** [comment]
待会我会上传最新的版本，测试可以使用
